[functions]
  node_bundler = "esbuild"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://app-center.netlify.app https://*.onrender.com"
[[redirects]]
  from = "https://music-online.netlify.app"
  to = "https://code-app.netlify.app/music/"
  status = 301